name: SSI Crawling

on:
  push:
    branches:
      - master
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the Github Actions Workflow page directly
  schedule:
    - cron: '0 16 * * *' # Run workflow every day at UTC+8 midnight

jobs:
  product-life-cycle-dates:
    name: Update SSI Product life cycle dates
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Run SSI Crawling
        uses: addnab/docker-run-action@v3
        with:
          image: ghcr.io/cage1016/ssi-crawling:0.2.3
          options: >
            --user root
            --env NUM_WORKERS=50
            --env INTERVAL_BASE=10
            --env INTERVAL_RANDOMIZATION=30
            --env MAX_RETRIES=2
            -v ${{ github.workspace }}:/tmp/:rw
            -w /tmp
          run: /layers/google.go.build/bin/main crawling -t Asia/Taipei
      - uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions            
